//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF_FirstRun.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XF_FirstRun.Resx.AppResx", typeof(AppResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_txt {
            get {
                return ResourceManager.GetString("About_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse_txt {
            get {
                return ResourceManager.GetString("Browse_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your local data DELETED!.
        /// </summary>
        internal static string DataDeleted_txt {
            get {
                return ResourceManager.GetString("DataDeleted_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your local  data NOT deletet!.
        /// </summary>
        internal static string DataNotDeleted_txt {
            get {
                return ResourceManager.GetString("DataNotDeleted_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You really want to dalete all local data?.
        /// </summary>
        internal static string DeleteData_txt {
            get {
                return ResourceManager.GetString("DeleteData_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World!.
        /// </summary>
        internal static string Hello_msg {
            get {
                return ResourceManager.GetString("Hello_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View 1.
        /// </summary>
        internal static string List_View_1_txt {
            get {
                return ResourceManager.GetString("List_View_1_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List # 0.
        /// </summary>
        internal static string List0_txt {
            get {
                return ResourceManager.GetString("List0_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List #1.
        /// </summary>
        internal static string List1_txt {
            get {
                return ResourceManager.GetString("List1_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok_btm {
            get {
                return ResourceManager.GetString("Ok_btm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language:.
        /// </summary>
        internal static string PickLng {
            get {
                return ResourceManager.GetString("PickLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language:.
        /// </summary>
        internal static string SelectLang_txt {
            get {
                return ResourceManager.GetString("SelectLang_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Data Saving Directory.
        /// </summary>
        internal static string Setting_Directory_txt {
            get {
                return ResourceManager.GetString("Setting_Directory_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings Page!.
        /// </summary>
        internal static string Setting_Header_txt {
            get {
                return ResourceManager.GetString("Setting_Header_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setting_SaveButton_txt {
            get {
                return ResourceManager.GetString("Setting_SaveButton_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Local  Data.
        /// </summary>
        internal static string Settings_EraseDataButton_txt {
            get {
                return ResourceManager.GetString("Settings_EraseDataButton_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Page.
        /// </summary>
        internal static string Settings_Title_txt {
            get {
                return ResourceManager.GetString("Settings_Title_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_txt {
            get {
                return ResourceManager.GetString("Settings_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPage_title {
            get {
                return ResourceManager.GetString("SettingsPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test message!.
        /// </summary>
        internal static string Test_msg {
            get {
                return ResourceManager.GetString("Test_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
